Refactor-code(Assignment 2.4)
Dhikshita-macherla/mle-training pull request #14
Opened 2024-03-26 13:03 UTC by Dhikshita-macherla

Hence closes #13 

- Created an issue and branch(enh/13/refactor-code)
-  Reformatted and refactored the provided script into a version that is production ready
- Separated data ingestion, training and scoring logic into different modules.
- Added more tests for verifying correct import of the above modules after building
- Wrokflow setup done
- Built the package
- Installed the package from the built .whl file
- Executed the installation tests using pytest.
- Created a PR

Screenshot
Workflow
<img width="941" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/d533f387-d3b2-4b24-add6-3edfe4a6e021">

Tree before build
<img width="703" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/15ad50b4-51a6-46c9-a7fb-6a93a5ef7337">

Tree after build
<img width="722" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/70725da9-5a05-45ed-a014-0cdea0d78cd2">

pytest op
<img width="715" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/bf7bbdd9-682d-48f9-857e-e4df4019619f">

2024-03-27 08:59 UTC, abilashravi-ta requested changes
Refactor your code in such a way that your final `main.py` (or `nonstandardcode.py`) looks something like this..

```
# import statements

# fetch data
# load data

# split data into train-data & test-data

# do preprocessing for train-data
# do preprocessing for test-data

# train all the models using train-data and save the trained-models
# print all the scoring metrics for train-data

# use the trained-models to predict on test-data
# print all the scoring metrics for train-data
```

2024-03-27 08:59 UTC, abilashravi-ta commented on src/housePricePrediction/data_training.py
> +    return housing_predictions
probably you could have name this as `train_data_regression()` to make it more intuitive.

2024-03-27 08:59 UTC, abilashravi-ta commented on nonstandardcode.py
> +from scipy.stats import randint
rename this file as `main.py` instead of `nonstandardcode.py`

2024-03-27 08:59 UTC, abilashravi-ta commented on src/housePricePrediction/data_ingestion.py
> +    housing["bedrooms_per_room"] = (
None of your function should take _train_ or _test_ specific data.

Ideally, most of the functions should be like
```
def func_name(X, y):
   ...
   ...
```
or
```
def func_name(full_data, X, y):
     ....
     ....
```
and then in `main.py` you should call theses function twice (for _train-data_ & _test-data_ seperately) like..
```
train_rmse = scoring_logic(train_X, train_y)
test_rmse = scoring_logic(test_X, test_y)
# and so on..
```

2024-03-27 08:59 UTC, abilashravi-ta commented on src/housePricePrediction/data_training.py
> +    X_test_cat = X_test[["ocean_proximity"]]
This full logic is already present in `data_ingestion.py`, so instead of writing it again put this block inside a separate function and call that function twice in `main.py`.
Avoid [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) coding style whenever possible.

2024-03-27 11:34 UTC, Dhikshita-macherla commented on src/housePricePrediction/data_training.py
> +    X_test_cat = X_test[["ocean_proximity"]]
I've corrected all the changes that you specified. Is this alright?

2024-03-28 04:29 UTC, abilashravi-ta requested changes
Your changes are almost correct.
Just make the below suggested modifications..

2024-03-28 04:29 UTC, abilashravi-ta commented on src/housePricePrediction/data_ingestion.py
> +    housing.plot(kind="scatter", x="longitude", y="latitude")
Are you not running `black` & `flake8`.?
There seems to be some spacing issue between 2 functions.

2024-03-28 04:29 UTC, abilashravi-ta commented on src/housePricePrediction/data_training.py
> +    return final_model
Can these 2 functions be combined together?
Because the only output that we need from these 2 functions is `final_model` so have just one like `cross_validated_estimators` which can do _RandamizedCV_ or _gridCV_ and return the _final model_ accordingly.

2024-03-28 04:29 UTC, abilashravi-ta commented on main.py
> +housing_train ,y_train, housing_prepared_train =data_ingestion.imputing_data(strat_train_set)
this naming is confusing.. probably you can have something like 
```
housing_train , housing_y_train, housing_x_train =data_ingestion.imputing_data(strat_train_set)
```
and for the sunbsequent lines as well.

2024-03-28 05:09 UTC, Dhikshita-macherla commented on main.py
> +housing_train ,y_train, housing_prepared_train =data_ingestion.imputing_data(strat_train_set)
I've changed all the corrections that you specified. Is this alright?

2024-03-28 05:20 UTC, abilashravi-ta requested changes

2024-03-28 05:20 UTC, abilashravi-ta commented on src/housePricePrediction/data_training.py
> +
why did u remove the `RandomSearchCV` part?

2024-03-28 05:32 UTC, Dhikshita-macherla commented on src/housePricePrediction/data_training.py
> +
I've added it back again now

2024-03-28 05:48 UTC, abilashravi-ta approved these changes

2024-03-28 05:49 UTC, merged