Unit Test -Assignment 2.5
Dhikshita-macherla/mle-training pull request #16
Opened 2024-03-28 08:16 UTC by Dhikshita-macherla

Hence closes #15 

- Created unit test case(s) for each module.
- Installed the package for the tests to run
- Created a github workflow job for building the package
- Installed the package in dev mode.
- Executed the tests using pytest.
- Created a PR

Screenshots
Workflow op
<img width="946" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/cc77e021-65b2-4fe8-b991-7a43e3498f6d">

Tree op
<img width="356" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/a0a20723-984c-4461-887e-53d486a668b4">

Pytest op
<img width="452" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/8da396eb-3302-4153-84ac-d6871a8580ad">

2024-03-29 04:50 UTC, abilashravi-ta requested changes

2024-03-29 04:50 UTC, abilashravi-ta commented on .github/workflows/unit_test.yml
> +      - test/15/unittest
remove multiple triggers

2024-03-29 04:50 UTC, abilashravi-ta commented on .github/workflows/unit_test.yml
> +
make this comand as `pytest -v` instead of just `pytest`. So that we get detailed test results.
Then update you PR with latest screenshots.

2024-03-29 04:50 UTC, abilashravi-ta commented on tests/unit_tests/test_data_training.py
> +            data_training.stratified_Shuffle_Split(self.data)
In _unit-test cases_ it's not a good idea to call 2 functions (in this case you have called `data_ingestion.load_housing_data()` and `data_training.stratified_Shuffle_Split()`). Instead you can just create a sample data like you have done in `test_imputing_data` and then call `data_training.stratified_Shuffle_Split()` on it.

2024-03-29 04:52 UTC, abilashravi-ta commented
@Dhikshita-macherla also always have some meaningful _commit-messages_.

![image](https://github.com/Dhikshita-macherla/mle-training/assets/53215532/de96fe82-5bd0-4f61-80ee-ffc2204ee29f)

2024-03-29 05:57 UTC, Dhikshita-macherla commented on tests/unit_tests/test_data_training.py
> +            data_training.stratified_Shuffle_Split(self.data)
I've corrected all the changes that you specified, can you please look at it?

2024-04-01 03:37 UTC, abilashravi-ta requested changes
@Dhikshita-macherla can you update the PR description with latest _workflow runs_.

2024-04-01 04:07 UTC, abilashravi-ta approved these changes

2024-04-01 04:08 UTC, merged