Assignment1.2
Dhikshita-macherla/mle-training pull request #2
Opened 2024-03-13 12:15 UTC by Dhikshita-macherla

Completed assignment 1.2
Kindly verify the same

2024-03-18 04:13 UTC, abilashravi-ta requested changes

2024-03-18 04:13 UTC, abilashravi-ta commented on README.md
> +conda env export >environment.yml <br>
These instructions seem to be wrong..

Ideally, these instructions should tell, anyone who'll be using using your repo, how to 
- clone the repo
- create _conda environment_ from the `envirenment.yml`
- run the script

2024-03-18 04:14 UTC, abilashravi-ta commented
@Dhikshita-macherla why is there a _merge conflict_ even for the first PR?

2024-03-18 07:16 UTC, Dhikshita-macherla commented on README.md
> +conda env export >environment.yml <br>
I've added the instruction in the README.md file as specified.
I changed the README.md file in main branch after pushing, so i got the merge conflict. Now I've resolved the conflicts. Can you please check and if I need to change anything else.

2024-03-18 10:42 UTC, abilashravi-ta requested changes

2024-03-18 10:42 UTC, abilashravi-ta commented on README.md
> +python nostandardcode.py<br>
@Dhikshita-macherla these instructions doesn't look correct..
Can you have a look at Satya or Sumyami's submission once for an idea.

2024-03-18 10:44 UTC, abilashravi-ta commented
Also please correct your [PR description](https://github.com/Dhikshita-macherla/mle-training/pull/2#issue-2183858923)

2024-03-18 11:42 UTC, Dhikshita-macherla commented on README.md
> +python nostandardcode.py<br>
I've changed the above correction. Can you please take a look at it.

2024-03-19 04:15 UTC, abilashravi-ta approved these changes
LGTM. You can _merge_ it to **main**.

@Dhikshita-macherla please make all the changes on _VSCode_ or _Terminal_ in local repository and then _push_ your changes to remote.
Don't directly commit on _GitHub_.

2024-03-19 04:15 UTC, abilashravi-ta commented on README.md
> +$conda env export >environment.yml<br>
This **Line 23** need not be part of the instructions to run the script..

2024-03-19 04:41 UTC, Dhikshita-macherla commented on README.md
> +$conda env export >environment.yml<br>
Okay, thank you Abilash.

2024-03-19 04:59 UTC, merged