Fixing errors in nonstandardcode.py using vscode
Dhikshita-macherla/mle-training pull request #6
Opened 2024-03-19 08:06 UTC by Dhikshita-macherla

Hence closes #5 
-Created an issue
-installed all the necessary packages in vs code
-Configured VSCode for Python development
- Configured the user and workspace settings
- Created a PR for the changes

Commands
$git checkout -b fix/5/vscode-refactor v0.1
$nano nonstandardcode.py
$ flake8 nonstandardcode.py
$black -l 79 --preview nonstandardcode.py
$isort nonstandardcode.py
$git add nonstandardcode.py
$ git commit -am "Fixed errors in nonstandardcode.py"
$git push origin fix/5/vscode-refactor

Screenshot
<img width="542" alt="image" src="https://github.com/Dhikshita-macherla/mle-training/assets/163232622/393f3d0d-6e7e-4ee8-a52a-726c74d41138">

Workspace settings
{
    "python.defaultInterpreterPath": "/home/dhikshita/miniconda3/bin/python",
    "editor.formatOnSave": false,
    "[python]": {
        "editor.formatOnType": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": "explicit"
        },
    },
    "flake8.args": [
        "--max-line-length=120"
    ]
}

User setting
{
    "isort.check": true,
    "python.linting.enabled": true,
    "python.linting.flake8Enabled": true,
    "[python]": {
        "editor.tabSize": 4,
        "editor.defaultFormatter": "ms-python.black-formatter",
    },
    "files.trimTrailingWhitespace": true,
    "flake8.args": [
        "--max-line-length=120",
    ],
}

2024-03-19 09:17 UTC, abilashravi-ta requested changes

2024-03-19 09:17 UTC, abilashravi-ta commented on .vscode/settings.json
> +    ],
Why is this `max-line-length` set to **120** while in `black` you have kept it as **79**.

2024-03-19 09:20 UTC, Dhikshita-macherla commented on .vscode/settings.json
> +    ],
While executing flake8 nonstandardcode.py, it showed there were more than 79 characters in a single line. So, I changed the flake8 arguments

2024-03-20 06:08 UTC, abilashravi-ta requested changes

2024-03-20 06:08 UTC, abilashravi-ta commented on .vscode/settings.json
> +    ],
Make the `max-line-length` as **79** for both `black` and `flake8`.

2024-03-20 06:28 UTC, Dhikshita-macherla commented on .vscode/settings.json
> +    ],
I've changed all the corrections, Can you check if its alright?

2024-03-20 06:32 UTC, abilashravi-ta approved these changes
LGTM.

2024-03-20 06:54 UTC, merged